apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: chess
  template:
    metadata:
      labels:
        app: chess
    spec:
      containers:
      - name: chess
        image: yash5090/chess:latest
        ports:
        - containerPort: 5000
